# Generated by Django 4.1.7 on 2023-06-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('CRIME', 'Crime'), ('CIÊNCIA', 'Ciência'), ('DRAMA', 'Drama'), ('FANTASIA', 'Fantasia'), ('FICÇÃO CIENTÍFICA', 'Ficção Científica'), ('MISTÉRIO', 'Mistério'), ('AUTORES NACIONAIS', 'Autores Nacionais'), ('ROMANCE', 'Romance'), ('ROMANCE DE ÉPOCA', 'Romance de Época'), ('SUSPENSE', 'Suspense'), ('TERROR', 'Terror')], default='', max_length=100),
        ),
    ]
